### ISSUE TITLE
SyntaxError: Unexpected identifier when running script

### ISSUE THREAD

**Issue by scottkidder** [DockYard/ember-i18n-to-intl-migrator#10]
Running the script produces this error:
```
SyntaxError: Unexpected identifier
    at new Function (<anonymous>)
    at Object.locales.forEach (/home/skidder/.nvm/versions/node/v10.11.0/lib/node_modules/ember-i18n-intl-migrator/lib/translation-transform.js:12:15)
    at Array.forEach (<anonymous>)
    at module.exports (/home/skidder/.nvm/versions/node/v10.11.0/lib/node_modules/ember-i18n-intl-migrator/lib/translation-transform.js:10:11)
    at Object.<anonymous> (/home/skidder/.nvm/versions/node/v10.11.0/lib/node_modules/ember-i18n-intl-migrator/bin/ember-i18n-intl-migrator.js:10:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by snewcomer** [comment]
@scottkidder Do you have the same setup as @0xadada?

**Comment by sbsurf** [comment]
I also get the `SyntaxError: Unexpected token import` exception. My set up is similar to @0xadada's, except I keep my translations in `.json` files. I import them with the help of [ember-cli-json-module](https://github.com/IvyApp/ember-cli-json-module).

My translations.js file looks like:

```
import Ember from "ember";
import coreFile from "./core";    // core.json file
import targetFile from "./t";       // t.json file

export default Ember.merge(coreFile, targetFile);
```

**Comment by scottkidder** [comment]
I only have one import and everything else is in `translations.js`

```
import validations from "./validations";

export default {
  validations,
  "accept": "Accept",
  "foo": "Foo",
  "bar": {
     "baz"
  }
```

**Comment by scottkidder** [comment]
Any ideas here? From ember-intl docs I gather that we don't need to use this trick and should be able to nest our resources in subdirectories to be auto-discovered. Is that correct?

**Comment by sbsurf** [comment]
I gave up on using this tool, and migrated things myself. Not too terrible.

**Comment by lookininward** [comment]
Still getting 'SyntaxError: Unexpected token import'

**Comment by scottkidder** [comment]
Yeah, I ended up doing the the same @sbsurf. It seems ember-intl supports importing nested directions inside `translations/` so doing an import isn't really necessary. [json2yaml](https://www.npmjs.com/package/json2yaml) worked great for converting to yaml with very little manual work.

**Comment by scottkidder** [comment]
I'm going to close this, but maybe there should be a bit of documentation on not supporting the various setups mentioned here.
