### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Mifrill** [DockYard/ember-i18n-to-intl-migrator#23]
```
yarn global add ember-i18n-intl-migrator
ember-i18n-intl-migrator

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at isPluralObject (/home/mifrill/.config/yarn/global/node_modules/ember-i18n-intl-migrator/lib/translation-transform.js:70:17)
    at Object.keys.forEach.key (/home/mifrill/.config/yarn/global/node_modules/ember-i18n-intl-migrator/lib/translation-transform.js:50:45)
    at Array.forEach (<anonymous>)
    at walk (/home/mifrill/.config/yarn/global/node_modules/ember-i18n-intl-migrator/lib/translation-transform.js:40:20)
    at Object.keys.forEach.key (/home/mifrill/.config/yarn/global/node_modules/ember-i18n-intl-migrator/lib/translation-transform.js:56:18)
    at Array.forEach (<anonymous>)
    at walk (/home/mifrill/.config/yarn/global/node_modules/ember-i18n-intl-migrator/lib/translation-transform.js:40:20)
    at Object.keys.forEach.key (/home/mifrill/.config/yarn/global/node_modules/ember-i18n-intl-migrator/lib/translation-transform.js:56:18)
    at Array.forEach (<anonymous>)

```

```
    "ember-source": "~2.14.0",

    "ember-i18n": "4.5.0",
    "ember-i18n-cp-validations": "^3.1.0",
    "ember-i18n-errors": "0.2.0",
```

**Comment by Mifrill** [comment]
Got the same issue on `"ember-source": "~3.2.0",`
Hello, @snewcomer are you able to help with it? Not sure what I'm doing wrong

**Comment by Mifrill** [comment]
okay, it looks like it's related to multiline strings concatenation, for example:
```js
{
	"jamesBond19": "The world" + 
	"Is Not Enough",
}
```
